# 2022-03-02 Costly Copy

## Setup

```{r}
experiment_slug <- "2022-03-02-costly-copy"
working_directory <- paste0("experiments/",experiment_slug,"/analysis/")
```

### Analysis dependencies

Load all required R libraries

```{r}
library(tidyverse)
library(ggplot2)
library(scales)
library(cowplot)
library(RColorBrewer)
source("https://gist.githubusercontent.com/benmarwick/2a1bb0133ff568cbe28d/raw/fb53bd97121f7f9ce947837ef1a4c65a73bffb3f/geom_flat_violin.R")
```

These analyses were knit with the following environment:

```{r}
print(version)
```

### Load data

Load summary data.

```{r}
summary_data_loc <- paste0(working_directory, "data/aggregate.csv")
summary_data <- read.csv(summary_data_loc, na.strings="NONE")


summary_data$env_cond <- as.factor(
  summary_data$env_cond
)
summary_data$MAX_HEAD_COPY_COST <- as.factor(
  summary_data$MAX_HEAD_COPY_COST
)
summary_data$COPY_MUT_PROB <- as.factor(
  summary_data$COPY_MUT_PROB
)
```

Load time series data.

```{r}
time_series_data_loc <- paste0(working_directory, "data/time_series_u0-u300000.csv")
time_series_data <- read.csv(time_series_data_loc, na.strings="NONE")

time_series_data$env_cond <- as.factor(
  time_series_data$env_cond
)
time_series_data$MAX_HEAD_COPY_COST <- as.factor(
  time_series_data$MAX_HEAD_COPY_COST
)
time_series_data$COPY_MUT_PROB <- as.factor(
  time_series_data$COPY_MUT_PROB
)
```

Miscellaneous setup.

```{r}
# Configure our default graphing theme
theme_set(theme_cowplot())
# Palette
cb_palette <- "Dark2"
alpha <- 0.05
# Create a directory to store plots
plot_directory <- paste0(working_directory, "plots/")
dir.create(plot_directory, showWarnings=FALSE)
```

## Final task match scores

```{r}
ggplot(
    summary_data,
    aes(
      x=MAX_HEAD_COPY_COST,
      y=dom_match_score_env_a,
      fill=MAX_HEAD_COPY_COST
    )
  ) +
  geom_flat_violin(
    position = position_nudge(x = .2, y = 0),
    alpha = .8,
    adjust=1.5
  ) +
  geom_point(
    mapping=aes(color=MAX_HEAD_COPY_COST),
    position = position_jitter(height=0.1, width = .15),
    size = .5,
    alpha = 0.8
  ) +
  geom_boxplot(
    width = .1,
    outlier.shape = NA,
    alpha = 0.5
  ) +
  scale_fill_brewer(
    palette=cb_palette
  ) +
  scale_color_brewer(
    palette=cb_palette
  ) +
  facet_grid(
    env_cond~COPY_MUT_PROB
  ) +
  scale_y_continuous(
    limits=c(-0.5, 7),
    breaks=c(0, 2, 4, 6)
  ) +
  theme(
    legend.position="none",
    axis.text=element_text(size=14),
    # axis.text.x = element_text(angle = 90),
    panel.border = element_rect(color = "grey", fill=NA, size=1.5)
  )
ggsave(
  paste0(working_directory, "plots/", "dom_match_score_env_a.pdf")
)
```

## Final mutation rates

```{r}
ggplot(
    summary_data,
    aes(
      x=MAX_HEAD_COPY_COST,
      y=final_average_copy_mutation_rate,
      fill=MAX_HEAD_COPY_COST
    )
  ) +
  geom_flat_violin(
    position = position_nudge(x = .2, y = 0),
    alpha = .8,
    adjust=1.5
  ) +
  geom_point(
    mapping=aes(color=MAX_HEAD_COPY_COST),
    size = .5,
    alpha = 0.8
  ) +
  geom_boxplot(
    width = .1,
    outlier.shape = NA,
    alpha = 0.5
  ) +
  scale_fill_brewer(
    palette=cb_palette
  ) +
  scale_color_brewer(
    palette=cb_palette
  ) +
  facet_grid(
    env_cond~COPY_MUT_PROB
  ) +
  scale_y_continuous(
    # trans=pseudo_log_trans(sigma=1,base=10)
    trans=log10_trans()
  ) +
  theme(
    legend.position="none",
    axis.text=element_text(size=14),
    # axis.text.x = element_text(angle = 90),
    panel.border = element_rect(color = "grey", fill=NA, size=1.5)
  )

ggsave(
  paste0(working_directory, "plots/", "final_average_copy_mutation_rate.pdf")
)
```

## Mutation rates over time

```{r}
ggplot(
    filter(time_series_data, (update%%1000)==0),
    aes(
      x=update,
      y=mutation_rates_average_copy_mutation_rate,
      fill=MAX_HEAD_COPY_COST,
      color=MAX_HEAD_COPY_COST
    )
  ) +
  stat_summary(geom="line", fun=mean) +
  stat_summary(
    geom="ribbon",
    fun.data="mean_cl_boot",
    fun.args=list(conf.int=0.95),
    alpha=0.2,
    linetype=0
  ) +
  scale_fill_brewer(
    palette=cb_palette
  ) +
  scale_color_brewer(
    palette=cb_palette
  ) +
  scale_y_continuous(
    trans=log10_trans()
  ) +
  facet_grid(
    env_cond~COPY_MUT_PROB
  ) +
  theme(
    legend.position="bottom",
    axis.text=element_text(size=14),
    # axis.text.x = element_text(angle = 90),
    panel.border = element_rect(color = "grey", fill=NA, size=1.5)
  )

ggsave(
  paste0(working_directory, "plots/", "average_copy_mutation_rate_ot.pdf"),
  width=20,
  height=20
)
ggsave(
  paste0(working_directory, "plots/", "average_copy_mutation_rate_ot.png"),
  width=10,
  height=10
)
```